version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"